/** Deterministic EN/ES country display names (Hermes-safe; no Intl.DisplayNames). */

export const COUNTRY_NAMES_EN: Readonly<Record<string, string>> = {
  "AD": 'Andorra',
  "AE": 'United Arab Emirates',
  "AF": 'Afghanistan',
  "AG": 'Antigua & Barbuda',
  "AI": 'Anguilla',
  "AL": 'Albania',
  "AM": 'Armenia',
  "AO": 'Angola',
  "AQ": 'Antarctica',
  "AR": 'Argentina',
  "AS": 'American Samoa',
  "AT": 'Austria',
  "AU": 'Australia',
  "AW": 'Aruba',
  "AX": 'Åland Islands',
  "AZ": 'Azerbaijan',
  "BA": 'Bosnia & Herzegovina',
  "BB": 'Barbados',
  "BD": 'Bangladesh',
  "BE": 'Belgium',
  "BF": 'Burkina Faso',
  "BG": 'Bulgaria',
  "BH": 'Bahrain',
  "BI": 'Burundi',
  "BJ": 'Benin',
  "BL": 'St. Barthélemy',
  "BM": 'Bermuda',
  "BN": 'Brunei',
  "BO": 'Bolivia',
  "BQ": 'Caribbean Netherlands',
  "BR": 'Brazil',
  "BS": 'Bahamas',
  "BT": 'Bhutan',
  "BV": 'Bouvet Island',
  "BW": 'Botswana',
  "BY": 'Belarus',
  "BZ": 'Belize',
  "CA": 'Canada',
  "CC": 'Cocos (Keeling) Islands',
  "CD": 'Congo - Kinshasa',
  "CF": 'Central African Republic',
  "CG": 'Congo - Brazzaville',
  "CH": 'Switzerland',
  "CI": 'Côte d’Ivoire',
  "CK": 'Cook Islands',
  "CL": 'Chile',
  "CM": 'Cameroon',
  "CN": 'China',
  "CO": 'Colombia',
  "CR": 'Costa Rica',
  "CU": 'Cuba',
  "CV": 'Cape Verde',
  "CW": 'Curaçao',
  "CX": 'Christmas Island',
  "CY": 'Cyprus',
  "CZ": 'Czechia',
  "DE": 'Germany',
  "DJ": 'Djibouti',
  "DK": 'Denmark',
  "DM": 'Dominica',
  "DO": 'Dominican Republic',
  "DZ": 'Algeria',
  "EC": 'Ecuador',
  "EE": 'Estonia',
  "EG": 'Egypt',
  "EH": 'Western Sahara',
  "ER": 'Eritrea',
  "ES": 'Spain',
  "ET": 'Ethiopia',
  "FI": 'Finland',
  "FJ": 'Fiji',
  "FK": 'Falkland Islands',
  "FM": 'Micronesia',
  "FO": 'Faroe Islands',
  "FR": 'France',
  "GA": 'Gabon',
  "GB": 'United Kingdom',
  "GD": 'Grenada',
  "GE": 'Georgia',
  "GF": 'French Guiana',
  "GG": 'Guernsey',
  "GH": 'Ghana',
  "GI": 'Gibraltar',
  "GL": 'Greenland',
  "GM": 'Gambia',
  "GN": 'Guinea',
  "GP": 'Guadeloupe',
  "GQ": 'Equatorial Guinea',
  "GR": 'Greece',
  "GS": 'South Georgia & South Sandwich Islands',
  "GT": 'Guatemala',
  "GU": 'Guam',
  "GW": 'Guinea-Bissau',
  "GY": 'Guyana',
  "HK": 'Hong Kong SAR China',
  "HM": 'Heard & McDonald Islands',
  "HN": 'Honduras',
  "HR": 'Croatia',
  "HT": 'Haiti',
  "HU": 'Hungary',
  "ID": 'Indonesia',
  "IE": 'Ireland',
  "IL": 'Israel',
  "IM": 'Isle of Man',
  "IN": 'India',
  "IO": 'British Indian Ocean Territory',
  "IQ": 'Iraq',
  "IR": 'Iran',
  "IS": 'Iceland',
  "IT": 'Italy',
  "JE": 'Jersey',
  "JM": 'Jamaica',
  "JO": 'Jordan',
  "JP": 'Japan',
  "KE": 'Kenya',
  "KG": 'Kyrgyzstan',
  "KH": 'Cambodia',
  "KI": 'Kiribati',
  "KM": 'Comoros',
  "KN": 'St. Kitts & Nevis',
  "KP": 'North Korea',
  "KR": 'South Korea',
  "KW": 'Kuwait',
  "KY": 'Cayman Islands',
  "KZ": 'Kazakhstan',
  "LA": 'Laos',
  "LB": 'Lebanon',
  "LC": 'St. Lucia',
  "LI": 'Liechtenstein',
  "LK": 'Sri Lanka',
  "LR": 'Liberia',
  "LS": 'Lesotho',
  "LT": 'Lithuania',
  "LU": 'Luxembourg',
  "LV": 'Latvia',
  "LY": 'Libya',
  "MA": 'Morocco',
  "MC": 'Monaco',
  "MD": 'Moldova',
  "ME": 'Montenegro',
  "MF": 'St. Martin',
  "MG": 'Madagascar',
  "MH": 'Marshall Islands',
  "MK": 'North Macedonia',
  "ML": 'Mali',
  "MM": 'Myanmar (Burma)',
  "MN": 'Mongolia',
  "MO": 'Macao SAR China',
  "MP": 'Northern Mariana Islands',
  "MQ": 'Martinique',
  "MR": 'Mauritania',
  "MS": 'Montserrat',
  "MT": 'Malta',
  "MU": 'Mauritius',
  "MV": 'Maldives',
  "MW": 'Malawi',
  "MX": 'Mexico',
  "MY": 'Malaysia',
  "MZ": 'Mozambique',
  "NA": 'Namibia',
  "NC": 'New Caledonia',
  "NE": 'Niger',
  "NF": 'Norfolk Island',
  "NG": 'Nigeria',
  "NI": 'Nicaragua',
  "NL": 'Netherlands',
  "NO": 'Norway',
  "NP": 'Nepal',
  "NR": 'Nauru',
  "NU": 'Niue',
  "NZ": 'New Zealand',
  "OM": 'Oman',
  "PA": 'Panama',
  "PE": 'Peru',
  "PF": 'French Polynesia',
  "PG": 'Papua New Guinea',
  "PH": 'Philippines',
  "PK": 'Pakistan',
  "PL": 'Poland',
  "PM": 'St. Pierre & Miquelon',
  "PN": 'Pitcairn Islands',
  "PR": 'Puerto Rico',
  "PS": 'Palestinian Territories',
  "PT": 'Portugal',
  "PW": 'Palau',
  "PY": 'Paraguay',
  "QA": 'Qatar',
  "RE": 'Réunion',
  "RO": 'Romania',
  "RS": 'Serbia',
  "RU": 'Russia',
  "RW": 'Rwanda',
  "SA": 'Saudi Arabia',
  "SB": 'Solomon Islands',
  "SC": 'Seychelles',
  "SD": 'Sudan',
  "SE": 'Sweden',
  "SG": 'Singapore',
  "SH": 'St. Helena',
  "SI": 'Slovenia',
  "SJ": 'Svalbard & Jan Mayen',
  "SK": 'Slovakia',
  "SL": 'Sierra Leone',
  "SM": 'San Marino',
  "SN": 'Senegal',
  "SO": 'Somalia',
  "SR": 'Suriname',
  "SS": 'South Sudan',
  "ST": 'São Tomé & Príncipe',
  "SV": 'El Salvador',
  "SX": 'Sint Maarten',
  "SY": 'Syria',
  "SZ": 'Eswatini',
  "TC": 'Turks & Caicos Islands',
  "TD": 'Chad',
  "TF": 'French Southern Territories',
  "TG": 'Togo',
  "TH": 'Thailand',
  "TJ": 'Tajikistan',
  "TK": 'Tokelau',
  "TL": 'Timor-Leste',
  "TM": 'Turkmenistan',
  "TN": 'Tunisia',
  "TO": 'Tonga',
  "TR": 'Türkiye',
  "TT": 'Trinidad & Tobago',
  "TV": 'Tuvalu',
  "TW": 'Taiwan',
  "TZ": 'Tanzania',
  "UA": 'Ukraine',
  "UG": 'Uganda',
  "UM": 'U.S. Outlying Islands',
  "US": 'United States',
  "UY": 'Uruguay',
  "UZ": 'Uzbekistan',
  "VA": 'Vatican City',
  "VC": 'St. Vincent & Grenadines',
  "VE": 'Venezuela',
  "VG": 'British Virgin Islands',
  "VI": 'U.S. Virgin Islands',
  "VN": 'Vietnam',
  "VU": 'Vanuatu',
  "WF": 'Wallis & Futuna',
  "WS": 'Samoa',
  "XK": 'Kosovo',
  "YE": 'Yemen',
  "YT": 'Mayotte',
  "ZA": 'South Africa',
  "ZM": 'Zambia',
  "ZW": 'Zimbabwe',
} as const;

export const COUNTRY_NAMES_ES: Readonly<Record<string, string>> = {
  "AD": 'Andorra',
  "AE": 'Emiratos Árabes Unidos',
  "AF": 'Afganistán',
  "AG": 'Antigua y Barbuda',
  "AI": 'Anguila',
  "AL": 'Albania',
  "AM": 'Armenia',
  "AO": 'Angola',
  "AQ": 'Antártida',
  "AR": 'Argentina',
  "AS": 'Samoa Americana',
  "AT": 'Austria',
  "AU": 'Australia',
  "AW": 'Aruba',
  "AX": 'Islas Aland',
  "AZ": 'Azerbaiyán',
  "BA": 'Bosnia y Herzegovina',
  "BB": 'Barbados',
  "BD": 'Bangladés',
  "BE": 'Bélgica',
  "BF": 'Burkina Faso',
  "BG": 'Bulgaria',
  "BH": 'Baréin',
  "BI": 'Burundi',
  "BJ": 'Benín',
  "BL": 'San Bartolomé',
  "BM": 'Bermudas',
  "BN": 'Brunéi',
  "BO": 'Bolivia',
  "BQ": 'Caribe neerlandés',
  "BR": 'Brasil',
  "BS": 'Bahamas',
  "BT": 'Bután',
  "BV": 'Isla Bouvet',
  "BW": 'Botsuana',
  "BY": 'Bielorrusia',
  "BZ": 'Belice',
  "CA": 'Canadá',
  "CC": 'Islas Cocos',
  "CD": 'República Democrática del Congo',
  "CF": 'República Centroafricana',
  "CG": 'Congo',
  "CH": 'Suiza',
  "CI": 'Côte d’Ivoire',
  "CK": 'Islas Cook',
  "CL": 'Chile',
  "CM": 'Camerún',
  "CN": 'China',
  "CO": 'Colombia',
  "CR": 'Costa Rica',
  "CU": 'Cuba',
  "CV": 'Cabo Verde',
  "CW": 'Curazao',
  "CX": 'Isla de Navidad',
  "CY": 'Chipre',
  "CZ": 'Chequia',
  "DE": 'Alemania',
  "DJ": 'Yibuti',
  "DK": 'Dinamarca',
  "DM": 'Dominica',
  "DO": 'República Dominicana',
  "DZ": 'Argelia',
  "EC": 'Ecuador',
  "EE": 'Estonia',
  "EG": 'Egipto',
  "EH": 'Sáhara Occidental',
  "ER": 'Eritrea',
  "ES": 'España',
  "ET": 'Etiopía',
  "FI": 'Finlandia',
  "FJ": 'Fiyi',
  "FK": 'Islas Malvinas',
  "FM": 'Micronesia',
  "FO": 'Islas Feroe',
  "FR": 'Francia',
  "GA": 'Gabón',
  "GB": 'Reino Unido',
  "GD": 'Granada',
  "GE": 'Georgia',
  "GF": 'Guayana Francesa',
  "GG": 'Guernesey',
  "GH": 'Ghana',
  "GI": 'Gibraltar',
  "GL": 'Groenlandia',
  "GM": 'Gambia',
  "GN": 'Guinea',
  "GP": 'Guadalupe',
  "GQ": 'Guinea Ecuatorial',
  "GR": 'Grecia',
  "GS": 'Islas Georgia del Sur y Sandwich del Sur',
  "GT": 'Guatemala',
  "GU": 'Guam',
  "GW": 'Guinea-Bisáu',
  "GY": 'Guyana',
  "HK": 'RAE de Hong Kong (China)',
  "HM": 'Islas Heard y McDonald',
  "HN": 'Honduras',
  "HR": 'Croacia',
  "HT": 'Haití',
  "HU": 'Hungría',
  "ID": 'Indonesia',
  "IE": 'Irlanda',
  "IL": 'Israel',
  "IM": 'Isla de Man',
  "IN": 'India',
  "IO": 'Territorio Británico del Océano Índico',
  "IQ": 'Irak',
  "IR": 'Irán',
  "IS": 'Islandia',
  "IT": 'Italia',
  "JE": 'Jersey',
  "JM": 'Jamaica',
  "JO": 'Jordania',
  "JP": 'Japón',
  "KE": 'Kenia',
  "KG": 'Kirguistán',
  "KH": 'Camboya',
  "KI": 'Kiribati',
  "KM": 'Comoras',
  "KN": 'San Cristóbal y Nieves',
  "KP": 'Corea del Norte',
  "KR": 'Corea del Sur',
  "KW": 'Kuwait',
  "KY": 'Islas Caimán',
  "KZ": 'Kazajistán',
  "LA": 'Laos',
  "LB": 'Líbano',
  "LC": 'Santa Lucía',
  "LI": 'Liechtenstein',
  "LK": 'Sri Lanka',
  "LR": 'Liberia',
  "LS": 'Lesoto',
  "LT": 'Lituania',
  "LU": 'Luxemburgo',
  "LV": 'Letonia',
  "LY": 'Libia',
  "MA": 'Marruecos',
  "MC": 'Mónaco',
  "MD": 'Moldavia',
  "ME": 'Montenegro',
  "MF": 'San Martín',
  "MG": 'Madagascar',
  "MH": 'Islas Marshall',
  "MK": 'Macedonia del Norte',
  "ML": 'Mali',
  "MM": 'Myanmar (Birmania)',
  "MN": 'Mongolia',
  "MO": 'RAE de Macao (China)',
  "MP": 'Islas Marianas del Norte',
  "MQ": 'Martinica',
  "MR": 'Mauritania',
  "MS": 'Montserrat',
  "MT": 'Malta',
  "MU": 'Mauricio',
  "MV": 'Maldivas',
  "MW": 'Malaui',
  "MX": 'México',
  "MY": 'Malasia',
  "MZ": 'Mozambique',
  "NA": 'Namibia',
  "NC": 'Nueva Caledonia',
  "NE": 'Níger',
  "NF": 'Isla Norfolk',
  "NG": 'Nigeria',
  "NI": 'Nicaragua',
  "NL": 'Países Bajos',
  "NO": 'Noruega',
  "NP": 'Nepal',
  "NR": 'Nauru',
  "NU": 'Niue',
  "NZ": 'Nueva Zelanda',
  "OM": 'Omán',
  "PA": 'Panamá',
  "PE": 'Perú',
  "PF": 'Polinesia Francesa',
  "PG": 'Papúa Nueva Guinea',
  "PH": 'Filipinas',
  "PK": 'Pakistán',
  "PL": 'Polonia',
  "PM": 'San Pedro y Miquelón',
  "PN": 'Islas Pitcairn',
  "PR": 'Puerto Rico',
  "PS": 'Territorios Palestinos',
  "PT": 'Portugal',
  "PW": 'Palaos',
  "PY": 'Paraguay',
  "QA": 'Catar',
  "RE": 'Reunión',
  "RO": 'Rumanía',
  "RS": 'Serbia',
  "RU": 'Rusia',
  "RW": 'Ruanda',
  "SA": 'Arabia Saudí',
  "SB": 'Islas Salomón',
  "SC": 'Seychelles',
  "SD": 'Sudán',
  "SE": 'Suecia',
  "SG": 'Singapur',
  "SH": 'Santa Elena',
  "SI": 'Eslovenia',
  "SJ": 'Svalbard y Jan Mayen',
  "SK": 'Eslovaquia',
  "SL": 'Sierra Leona',
  "SM": 'San Marino',
  "SN": 'Senegal',
  "SO": 'Somalia',
  "SR": 'Surinam',
  "SS": 'Sudán del Sur',
  "ST": 'Santo Tomé y Príncipe',
  "SV": 'El Salvador',
  "SX": 'Sint Maarten',
  "SY": 'Siria',
  "SZ": 'Esuatini',
  "TC": 'Islas Turcas y Caicos',
  "TD": 'Chad',
  "TF": 'Territorios Australes Franceses',
  "TG": 'Togo',
  "TH": 'Tailandia',
  "TJ": 'Tayikistán',
  "TK": 'Tokelau',
  "TL": 'Timor-Leste',
  "TM": 'Turkmenistán',
  "TN": 'Túnez',
  "TO": 'Tonga',
  "TR": 'Turquía',
  "TT": 'Trinidad y Tobago',
  "TV": 'Tuvalu',
  "TW": 'Taiwán',
  "TZ": 'Tanzania',
  "UA": 'Ucrania',
  "UG": 'Uganda',
  "UM": 'Islas menores alejadas de EE. UU.',
  "US": 'Estados Unidos',
  "UY": 'Uruguay',
  "UZ": 'Uzbekistán',
  "VA": 'Ciudad del Vaticano',
  "VC": 'San Vicente y las Granadinas',
  "VE": 'Venezuela',
  "VG": 'Islas Vírgenes Británicas',
  "VI": 'Islas Vírgenes de EE. UU.',
  "VN": 'Vietnam',
  "VU": 'Vanuatu',
  "WF": 'Wallis y Futuna',
  "WS": 'Samoa',
  "XK": 'Kosovo',
  "YE": 'Yemen',
  "YT": 'Mayotte',
  "ZA": 'Sudáfrica',
  "ZM": 'Zambia',
  "ZW": 'Zimbabue',
} as const;
